In [1]:
##importing required libraries for data analysis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
##open csv file
df=pd.read_csv('car data snehith.csv')
df.columns=df.columns.map(str.lower)

In [5]:
df

car_name  year  selling_price  present_price  kms_driven fuel_type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    seller_type transmission  owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0  
2        Dealer       Manual      0  
3        Dealer       Manual      0  
4        Dealer       Manual      0  
..          ...          ...    ...  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0  

[301 rows x 9 columns]

In [6]:
##checking data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   car_name       301 non-null    object 
 1   year           301 non-null    int64  
 2   selling_price  301 non-null    float64
 3   present_price  301 non-null    float64
 4   kms_driven     301 non-null    int64  
 5   fuel_type      301 non-null    object 
 6   seller_type    301 non-null    object 
 7   transmission   301 non-null    object 
 8   owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [7]:
df.shape

(301, 9)

In [8]:
df.describe()

year  selling_price  present_price     kms_driven       owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [9]:
## checking null values
df.isna().sum()

car_name         0
year             0
selling_price    0
present_price    0
kms_driven       0
fuel_type        0
seller_type      0
transmission     0
owner            0
dtype: int64

In [11]:
df['owner'].value_counts()

owner
0    290
1     10
3      1
Name: count, dtype: int64

In [13]:
df['owner'].unique()

array([0, 1, 3], dtype=int64)

In [14]:
df['transmission'].value_counts()

transmission
Manual       261
Automatic     40
Name: count, dtype: int64

In [15]:
df['seller_type'].value_counts()

seller_type
Dealer        195
Individual    106
Name: count, dtype: int64

In [21]:
df['fuel_type'].value_counts()

fuel_type
2    239
1     60
0      2
Name: count, dtype: int64

In [20]:
##mapping
df['fuel_type'] = df['fuel_type'].map({'CNG':0,'Diesel':1,'Petrol':2}).astype(int)


IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [22]:
df['transmission']=df['transmission'].map({'Automatic':0,'Manual':1}).astype(int)

In [23]:
df['seller_type']=df['seller_type'].map({'Dealer':0,'Individual':1}).astype(int)

In [24]:
df.dtypes

car_name          object
year               int64
selling_price    float64
present_price    float64
kms_driven         int64
fuel_type          int32
seller_type        int32
transmission       int32
owner              int64
dtype: object

NameError: name 'df' is not defined

## segregate data set into x and  y 


In [25]:
x=df.iloc[:,3:]
print(x)

     present_price  kms_driven  fuel_type  seller_type  transmission  owner
0             5.59       27000          2            0             1      0
1             9.54       43000          1            0             1      0
2             9.85        6900          2            0             1      0
3             4.15        5200          2            0             1      0
4             6.87       42450          1            0             1      0
..             ...         ...        ...          ...           ...    ...
296          11.60       33988          1            0             1      0
297           5.90       60000          2            0             1      0
298          11.00       87934          2            0             1      0
299          12.50        9000          1            0             1      0
300           5.90        5464          2            0             1      0

[301 rows x 6 columns]


In [26]:
y=df['selling_price']
print(y)

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...  
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: selling_price, Length: 301, dtype: float64


## training and testing the data

In [28]:
from sklearn .model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

## feature scaling

In [30]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)


In [31]:
print(x_train)

[[-0.75393664 -0.55427944  0.47434165  1.30799212  0.36927447 -0.14400979]
 [ 0.67391682 -0.21078473  0.47434165 -0.7645306   0.36927447 -0.14400979]
 [-0.5875599   2.15059345  0.47434165  1.30799212  0.36927447 -0.14400979]
 ...
 [-0.62990629 -0.57843009  0.47434165  1.30799212  0.36927447 -0.14400979]
 [-0.37917108  0.6532531   0.47434165 -0.7645306   0.36927447 -0.14400979]
 [-0.77031801 -0.58567529  0.47434165  1.30799212  0.36927447 -0.14400979]]


In [32]:
print(x_test)

[[ 0.20587776  0.56585189 -1.8973666  -0.7645306   0.36927447 -0.14400979]
 [-0.74959057 -0.7716353   0.47434165  1.30799212  0.36927447 -0.14400979]
 [-0.20644237 -0.32054944  0.47434165 -0.7645306   0.36927447 -0.14400979]
 [ 0.45104108 -0.09570688 -1.8973666  -0.7645306   0.36927447 -0.14400979]
 [ 1.3614885  -0.55427944 -1.8973666  -0.7645306  -2.7080128  -0.14400979]
 [-0.17635415 -0.78129556  0.47434165 -0.7645306   0.36927447 -0.14400979]
 [-0.08497509 -0.07126642  0.47434165 -0.7645306   0.36927447 -0.14400979]
 [-0.78034742 -0.89238855  0.47434165  1.30799212  0.36927447 -0.14400979]
 [-0.08497509 -0.14371838  0.47434165 -0.7645306  -2.7080128  -0.14400979]
 [ 0.20587776 -0.04470071  0.47434165 -0.7645306   0.36927447 -0.14400979]
 [-0.32902403 -0.372739    0.47434165 -0.7645306   0.36927447 -0.14400979]
 [-0.73577227 -0.90446388  0.47434165  1.30799212  0.36927447 -0.14400979]
 [-0.20644237 -0.43077301  0.47434165 -0.7645306   0.36927447 -0.14400979]
 [ 0.26605421 -0.55427944

In [33]:
x_train.shape

(225, 6)

In [34]:
x_test.shape

(76, 6)

## Model Selection

In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor

In [36]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

## Linear Regression

In [40]:
lc=LinearRegression()
lc.fit(x_train,y_train)

LinearRegression()

In [42]:
y_pred=lc.predict(x_test)


In [45]:
mean_absolute_error(y_test,y_pred)

1.3970818221669763

In [46]:
mean_squared_error(y_test,y_pred)

5.62700750462096

In [47]:
np.sqrt(mean_squared_error(y_test,y_pred))

2.3721314265067526

In [55]:
r2_score(y_test,y_pred)

0.823967538211766

In [51]:
adj_r2 = (1 - (1 - r2) * ((x_train.shape[0] - 1) / 
          (x_train.shape[0] - x_train.shape[1] - 1)))

In [53]:
adj_r2,r2

(0.8191226080708055, 0.823967538211766)

## k Nearest Neighbour

In [56]:
knn=KNeighborsRegressor()
knn.fit(x_train,y_train)

KNeighborsRegressor()

In [57]:
y_pred=knn.predict(x_test)
print(y_pred)

[ 5.21   0.54   4.01   7.47  20.85   4.56   3.76   0.7    5.98   4.77
  3.58   1.05   4.57   8.27   6.64   8.24   7.01   4.17   0.48   1.42
  5.98   0.97   5.98   8.86   0.274  0.67   0.254  0.498  0.504  6.73
  0.97   6.2    0.498  7.     3.17   0.98   5.89   5.45   0.97   9.12
  8.956 20.     4.56   0.97   5.45  10.146  0.392  0.78   3.61   5.42
  8.27   3.6    3.11  20.     0.972  0.522  0.536  3.04   2.85   0.97
  4.64   6.27   3.5   21.7    3.76   4.57   7.76   6.12   0.396  3.89
  3.5    2.66   0.56   6.32   1.398  1.16 ]


In [58]:
print(x_test)

[[ 0.20587776  0.56585189 -1.8973666  -0.7645306   0.36927447 -0.14400979]
 [-0.74959057 -0.7716353   0.47434165  1.30799212  0.36927447 -0.14400979]
 [-0.20644237 -0.32054944  0.47434165 -0.7645306   0.36927447 -0.14400979]
 [ 0.45104108 -0.09570688 -1.8973666  -0.7645306   0.36927447 -0.14400979]
 [ 1.3614885  -0.55427944 -1.8973666  -0.7645306  -2.7080128  -0.14400979]
 [-0.17635415 -0.78129556  0.47434165 -0.7645306   0.36927447 -0.14400979]
 [-0.08497509 -0.07126642  0.47434165 -0.7645306   0.36927447 -0.14400979]
 [-0.78034742 -0.89238855  0.47434165  1.30799212  0.36927447 -0.14400979]
 [-0.08497509 -0.14371838  0.47434165 -0.7645306  -2.7080128  -0.14400979]
 [ 0.20587776 -0.04470071  0.47434165 -0.7645306   0.36927447 -0.14400979]
 [-0.32902403 -0.372739    0.47434165 -0.7645306   0.36927447 -0.14400979]
 [-0.73577227 -0.90446388  0.47434165  1.30799212  0.36927447 -0.14400979]
 [-0.20644237 -0.43077301  0.47434165 -0.7645306   0.36927447 -0.14400979]
 [ 0.26605421 -0.55427944

In [59]:
y_pred.shape

(76,)

In [61]:
x_test.shape

(76, 6)

In [62]:
mean_absolute_error(y_test,y_pred)

1.2926315789473684

In [64]:
MSE=mean_squared_error(y_test,y_pred)
RMSE=np.sqrt(mean_squared_error(y_test,y_pred))
R2=r2_score(y_test,y_pred)
print(MSE,RMSE,R2)

5.572647578947367 2.3606455852048964 0.8256681066810794


In [67]:
adj_r2 = (1 - (1 - R2) * ((x_train.shape[0] - 1) / 
          (x_train.shape[0] - x_train.shape[1] - 1)))

In [68]:
adj_r2

0.8208699811768889

  #SVM

In [69]:
svm=SVR()
svm.fit(x_train,y_train)

SVR()

In [70]:
y_pred=svm.predict(x_test)

In [73]:
MAE=mean_absolute_error(y_test,y_pred)
MSE=mean_squared_error(y_test,y_pred)
RMSE=np.sqrt(mean_squared_error(y_test,y_pred))
R2=r2_score(y_test,y_pred)
print(MAE,MSE,RMSE,R2)

1.7793786264752787 15.444418995060019 3.9299388029662774 0.5168445937993267


##DECISION TREE

In [75]:
dt=DecisionTreeRegressor(random_state=123)
dt.fit(x_train,y_train)

DecisionTreeRegressor(random_state=123)

In [76]:
y_pred=dt.predict(x_test)

In [77]:
MAE=mean_absolute_error(y_test,y_pred)
MSE=mean_squared_error(y_test,y_pred)
RMSE=np.sqrt(mean_squared_error(y_test,y_pred))
R2=r2_score(y_test,y_pred)
print(MAE,MSE,RMSE,R2)

1.023092105263158 3.2774088815789475 1.8103615333902086 0.897471195260148


##Random Forest


In [78]:
rf=RandomForestRegressor(n_estimators= 10,random_state=123)
rf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=123)

In [79]:
y_pred=rf.predict(x_test)

In [80]:
MAE=mean_absolute_error(y_test,y_pred)
MSE=mean_squared_error(y_test,y_pred)
RMSE=np.sqrt(mean_squared_error(y_test,y_pred))
R2=r2_score(y_test,y_pred)
print(MAE,MSE,RMSE,R2)

0.9599791666666668 3.367403344755117 1.8350485946576773 0.8946558539109135
